  - block:

    - name: Java Corretto | Add GPG key to apt keyring
      apt_key: url=https://apt.corretto.aws/corretto.key  state=present
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - java

    - name: Java Corretto | Add Debian apt repository
      apt_repository: repo="deb https://apt.corretto.aws stable main" state=present update_cache=yes
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - java

    - name: Java Corretto | Install
      apt: update-cache=yes pkg="java-{{ java_version | default('1.8.0') }}-amazon-corretto-jdk" state=present
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - java
    when: ansible_os_family == "Debian"

  - block:

    - name: Java Corretto | Yum repository
      yum_repository:
        name: corretto
        description: Amazon Corretto
        baseurl: "https://yum.corretto.aws/$basearch"
        gpgcheck: yes
        gpgkey: "https://yum.corretto.aws/corretto.key"
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - java

    - name: Java Corretto | Enable Import RPM key
      rpm_key:
        key: "https://yum.corretto.aws/corretto.key"
        state: present
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - java

    - name: Install packages
      package:
        name: "java-{{ java_version | default('1.8.0') }}-amazon-corretto-devel"
        state: present
      retries: 3
      register: result
      until: result is not failed
      become: yes
      tags:
        - java

    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

