---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
# lint:
#   name: yamllint
platforms:
  # - name: trusty
  #   box: ubuntu/trusty64
  #   # interfaces:
  #   #   - network_name: public_network
  #   #     type: dhcp
  #   #     auto_config: true    
  #  - name: xenial
  #    box: ubuntu/xenial64
  #    memory: 1024
  # - name: bionic
  #   box: ubuntu/bionic64
  #   memory: 1024
    # interfaces:
    #   - network_name: public_network
    #     type: dhcp
    #     auto_config: true
  # - name: centos6
  #   box: centos/6    
  - name: centos7
    box: centos/7
    memory: 1024
  # - name: fedora28
  #   box: generic/fedora28
  # - name: alpine
  #   box: generic/alpine28

    
provisioner:
  name: ansible
  # lint:
  #   name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
